version: '3'

services:
  livescorescore:
    image: livescorescore
    build:
      context: ./LiveScoresCore
      dockerfile: Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: ./../WebApplication1
      dockerfile: Dockerfile
